### ISSUE TITLE
ZFLineChart放置于cell中,无法显示

### ISSUE THREAD

**Issue by iPhilly** [Zirkfied/ZFChart#27]
chart的dataSource和delegate 是cell.
cell创建的同时跟随着创建chart这个subView,
而此时cell的valueArray还未被赋值.chart调动数据源方法,返回nil,
绘制完图表,cell的valueArray才被赋值,晚了.

这个问题,有没有什么好的解决方案啊?

**Comment by iPhilly** [comment]
我又尝试把chart的数据源设置为tableView的控制器,但是无法让cell和控制器的数组一一对应. 本来想给chart通过绑定tag来确定,不知道怎么绑定,同样是因为方法调用时机的问题. (head big!)

**Comment by Zirkfied** [comment]
在cell有数据后才调用strokePath方法

**Comment by iPhilly** [comment]
用了个很不套路的方法,竟然搞定了. 按你提示,准备再做一遍.谢谢

**Comment by Zirkfied** [comment]
你第一次的逻辑没问题的，就是拿到数据后调strokePath就好了，跟tableView的reloadData一个原理
