### ISSUE TITLE
Negative (<0) values in BarChart

### ISSUE THREAD

**Issue by skuske** [Zirkfied/ZFChart#31]
BarChart does not support bars with negative values (<0):

![img_3588](https://cloud.githubusercontent.com/assets/12996815/19715477/ba6a4710-9b55-11e6-9658-527b6a7eae7d.PNG)

**Comment by Zirkfied** [comment]
Did you set the "isResetAxisLineMinValue" to YES?

**Comment by skuske** [comment]
Thanks, I was using an old version. The current version fixed it. :)
