### ISSUE TITLE
Y-Axis double labels

### ISSUE THREAD

**Issue by skuske** [Zirkfied/ZFChart#43]
Any way to avoid this?

![image1-2](https://cloud.githubusercontent.com/assets/12996815/22237793/4db25ac2-e20e-11e6-9d53-e37cdcbb845d.PNG)

**Comment by hirents** [comment]
Hello,
What about this double label on Y-Axis.
Is there any solution?

**Comment by Zirkfied** [comment]
There is a property called "valueType", set valueType = kValueTypeDecimal;
And you can set another property, called "numberOfDecimal" to control the number of decimal.

**Comment by hirents** [comment]
Yes, it works,
I didn't add this property,
Thanks.
