### ISSUE TITLE
用linechart的时候会根据数值,图形会自动变成折线或者曲线,能固定选择一种吗,我只想他是折线

### ISSUE THREAD

**Issue by linhongmin1027** [Zirkfied/ZFChart#52]

**Comment by linhongmin1027** [comment]
kLinePatternTypeForSharp = 0,   //直线样式(默认样式)
    kLinePatternTypeForCurve = 1    //曲线样式
设置这个没效果哦

**Comment by Zirkfied** [comment]
Demo有效果没？

**Comment by linhongmin1027** [comment]
我有很多控制器有linechart,就建了个基类,在基类里面设置的,子控制器没这个效果,后来在每个子控制器里面设置才有了直线效果,不好意思,打扰了

**Comment by linhongmin1027** [comment]
1
