### ISSUE TITLE
How to auto scroll at last position x axis in linechart ?

### ISSUE THREAD

**Issue by hirents** [Zirkfied/ZFChart#66]
Hello,
I'm using line chart in completely worked for me.
But one problem is, I've set multiple values at x axis and it's setup and also scrolls good, but graph start with the first position of x axis value but I want to show the graph at last value of x axis in position.
Thanks in advance.

**Comment by Zirkfied** [comment]
Use the ZFGenericChartDataSource's method, called 
| - (NSInteger)axisLineStartToDisplayValueAtIndex:(ZFGenericChart *)chart | ...

and return a negative integer number, like -7

**Comment by Zirkfied** [comment]
Sorry, I forgot to upload the code when I finished the code. Now you can find the method.

**Comment by hirents** [comment]
Yes, Now it's works.
Thanks.
