### ISSUE TITLE
波浪图的数值能不能隐藏呢

### ISSUE THREAD

**Issue by Doraemontree** [Zirkfied/ZFChart#99]
波浪图的点太密集了，可否隐藏它的值

**Comment by Zirkfied** [comment]
有属性的，你仔细看看父类




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zirkfied/ZFChart"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月10日(星期五) 下午4:01
收件人:&nbsp;"Zirkfied/ZFChart"<ZFChart@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Zirkfied/ZFChart] 波浪图的数值能不能隐藏呢 (#99)





 
波浪图的点太密集了，可否隐藏它的值
